$window.current.maximize();setTimeout(function(){setTimeout(function(){$log('█    █')}, 100);
setTimeout(function(){$log('█    █')}, 200);
setTimeout(function(){$log(' █  █')}, 300);
setTimeout(function(){$log('  ██')}, 400);
setTimeout(function(){$log('  ||')}, 500);
setTimeout(function(){$log(' █  █')}, 600);
setTimeout(function(){$log('█    █')}, 700);
setTimeout(function(){$log('█    █')}, 800);
setTimeout(function(){$log('██   █')}, 900);
setTimeout(function(){$log('███ ██')}, 1000);
setTimeout(function(){$log('██████')}, 1100);
setTimeout(function(){$log('███ ██')}, 1200);
setTimeout(function(){$log('██   █')}, 1300);
setTimeout(function(){$log('███  █')}, 1400);
setTimeout(function(){$log('████ █')}, 1500);
setTimeout(function(){$log('██████')}, 1600);
setTimeout(function(){$log('██████')}, 1700);
setTimeout(function(){$log('█    █')}, 1800);
setTimeout(function(){$log('█    ██')}, 1900);
setTimeout(function(){$log('█     █')}, 2000);
setTimeout(function(){$log('█     ██')}, 2100);
setTimeout(function(){$log('█      █')}, 2200);
setTimeout(function(){$log('█      ██')}, 2300);
setTimeout(function(){$log('█       █')}, 2400);
setTimeout(function(){$log('███     █')}, 2500);
setTimeout(function(){$log('█████   █')}, 2600);
setTimeout(function(){$log('██████  █')}, 2700);
setTimeout(function(){$log('███████ █')}, 2800);
setTimeout(function(){$log('█████████')}, 2900);
setTimeout(function(){$log('█████████')}, 3000);
setTimeout(function(){$log('█   █   █')}, 3100);
setTimeout(function(){$log('█   █   █')}, 3200);
setTimeout(function(){$log('█   █   █')}, 3300);
setTimeout(function(){$log('█   █   █')}, 3400);
setTimeout(function(){$log('█   █   █')}, 3500);
setTimeout(function(){$log('█  █ █  █')}, 3600);
setTimeout(function(){$log('█ █ █ █ █')}, 3700);
setTimeout(function(){$log('██  █  ██')}, 3800);
setTimeout(function(){$log('███   ███')}, 3900);
setTimeout(function(){$log('█ █   █ █')}, 4000);
setTimeout(function(){$log('█ ██ ██ █')}, 4100);
setTimeout(function(){$log('█  ███  █')}, 4200);
setTimeout(function(){$log('█████████')}, 4300);
setTimeout(function(){$log('█       ██████')}, 4400);
setTimeout(function(){$log('█        █████')}, 4500);
setTimeout(function(){$log('█            █')}, 4600);
setTimeout(function(){$log('██████████████')}, 4700);
setTimeout(function(){$log('██████     ███')}, 4800);
setTimeout(function(){$log('███     ██████')}, 4900);
setTimeout(function(){$log('█            █')}, 5000);
setTimeout(function(){$log('█  ████████')}, 5100);
setTimeout(function(){$log('█  █      █  █')}, 5200);
setTimeout(function(){$log('█  █ ████ █  █')}, 5300);
setTimeout(function(){$log('█  █ █  █ █  █')}, 5400);
setTimeout(function(){$log('████ ████ ████')}, 5500);
setTimeout(function(){$log('              ')}, 5600);
setTimeout(function(){$log('  ██ ██   ███  ████  ████    ████  █   █   ')}, 5700);
setTimeout(function(){$log(' █  █  █ █   █ █   █ █       █   █ █   █   ')}, 5800);
setTimeout(function(){$log(' █  █  █ █████ █   █ ████    ████  █████   ')}, 5900);
setTimeout(function(){$log(' █  █  █ █   █ █   █ █       █   █   █     ')}, 6000);
setTimeout(function(){$log(' █  █  █ █   █ ████  ████    ████    █     ')}, 6100);
setTimeout(function(){$log('                                  ')}, 6200);
setTimeout(function(){$log(' ████  █      ████   ████ █   █ █     █   █       ')}, 6300);
setTimeout(function(){$log(' █   █ █     █    █ █     █  █  █     █   █       ')}, 6400);
setTimeout(function(){$log(' ████  █     █    █ █     ███   █     █████       ')}, 6500);
setTimeout(function(){$log(' █   █ █     █    █ █     █  █  █       █         ')}, 6600);
setTimeout(function(){$log(' ████  █████  ████   ████ █   █ █████   █         ')}, 6700);
setTimeout(function(){$log('                  :::             ')}, 6800);
setTimeout(function(){$log('                 :::              ')}, 6900);
setTimeout(function(){$log('                  :::             ')}, 7000);
setTimeout(function(){$log('                  :::             ')}, 7100);
setTimeout(function(){$log('                  ███             ')}, 7200);
setTimeout(function(){$log('                  ███             ')}, 7300);
setTimeout(function(){$log('  ████████████████████████████           ')}, 7400);
setTimeout(function(){$log('  ████████████████████████████         ')}, 7500);
setTimeout(function(){$log('  ████████████████████████████           ')}, 7600);
setTimeout(function(){$log('  ████   ████   █████   ██████           ')}, 7700);
setTimeout(function(){$log('  ████████████████████████████                      ')}, 7800);
setTimeout(function(){$log('  ████████████████████████████                      ')}, 7900);
setTimeout(function(){$log('  ████████████████████████████                      ')}, 8000);
setTimeout(function(){$log('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~@@@@@@')}, 8100);
setTimeout(function(){$log('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~@@@@@@@@@@@@@@@@@@@@@@@@')}, 8200);
setTimeout(function(){$log(' @~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')}, 8300);
setTimeout(function(){$log('@@ ~~ @@ ~~~~~~~~~~~~~~~~~~~~~ @@@@ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')}, 8400);
setTimeout(function(){$log('~~~~ @@@~ ~ @@ . @@@@ . @@@@ @@@@@@ @@@@@@::::::::::::::::::::@@@@@@@')}, 8500);
setTimeout(function(){$log('~~~~~~ @@@@ ~ ~ @@@@@ @@@@@@ @@@@@@ @:::::::::::::::::::::::::@@@@@@@')}, 8600);
setTimeout(function(){$log(',, ~ ~ ~~ @|||||@@@[][@@@@@;;@@  @@ ::::::::::::::::::::::::::@@@@@@@')}, 8700);
setTimeout(function(){$log('~~ ~ ,,, ~ ~ ~ ~ ~ ,, @ ~ ,, @@@@@@ ::::::::::::::::::::::::::@@@@@@@')}, 8800);
setTimeout(function(){$log('~~ ~ ,~ ~ ,,,,~ ,,,,, ,,,,,, @@@@@@ ::::::::@@::::::@@::::::::@@@@@@@')}, 8900);
setTimeout(function(){$log('~~ ~ ~ ~~ ,,,,~ ,,,,, ,,,,,, @@@@@@ :::::::@@@@::::@@@@:::::::@@@@@@@')}, 9000);
setTimeout(function(){$log(',, ` ` `` , ~ ~ ,,, ~ ,,,,,, @@  @@ :::::::@@@@::::@@@@:::::::@@@@@@@')}, 9100);
setTimeout(function(){$log('` `` ,,,`````````` ,, , ~ ,, @@@@@@ :::::::@@@@::::@@@@:::::::@@@@@@@')}, 9200);
setTimeout(function(){$log('` `` , `` ,,,,` ,,,,, ,,,,,, @@@@@@ ::::::::@@::::::@@::::::::@@@@@@@')}, 9300);
setTimeout(function(){$log('@ , , , , ,,, ~,,,,, ,,,,,,h @@@@ . ::::::::::::::::::::::::::@@@@@@@')}, 9400);
setTimeout(function(){$log('@@ -- @@ - - -p , - - ,,, - - =@@@@ ::@::::::::::::::::::::@::@@@@@@@')}, 9500);
setTimeout(function(){$log('- -  @@@ . .@@ . @@@@ . @@@@ @@@@@@ :::@::::::::::::::::::@:::@@@@@@@')}, 9600);
setTimeout(function(){$log('----------@@@@. @@@@@ @@@@@@ @@@@@@ ::::@@::::::::::::::@@::::@@@@@@@')}, 9700);
setTimeout(function(){$log(',,- - - - @ - - @@@ - @@@@@ -@@  @@ ::::::@@::::::::::@@::::::@@@@@@@')}, 9800);
setTimeout(function(){$log('-- - ,,,-- - - - - ,, @ , ,, @@@@@@ :::::::::@@@@@@@@:::::::::@@@@@@@')}, 9900);
setTimeout(function(){$log(',, , ,, , ,,,,, ,,,,, ,,,,,, @@@@@@ ::::::::::::::::::::::::::@@@@@@@')}, 10000);
setTimeout(function(){$log(',, , , ,, ,,, , ,,,,, ,,,,,, @@@@ . ::::::::::::::::::::::::::@@@@@@@')}, 10100);
setTimeout(function(){$log(',,,,,,,,,,,,,,,,,,,,,,, , ,, , @@@@ ::::::::::::::::::::::::::@@@@@@@')}, 10200);
setTimeout(function(){$log(',,,, ,,,. , ,, , ,,,, , ,,,, @@@@@@ ::::::@@@@@@@@@@@@@@@@@@@:@@@@@@@')}, 10300);
setTimeout(function(){$log('..........,,,,, ,,,,, ,,,,,, @@@@@@ :@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')}, 10400);
setTimeout(function(){$log('@@, , , , , , , ,,,,, ,,,,, .@@  @@ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')}, 10500);
setTimeout(function(){$log('. ,. @@@ . ,. .... @@ ,, ,@@ @@@@@@ @@@@@@@@@ . . . . . . .@@@@@@@@@@')}, 10600);
setTimeout(function(){$log(', ,, @ !! @@@@@ @@@@@ @@@@@@ @@@@@@ @@ . . . . . . . . . . . . . @@@@')}, 10700);
setTimeout(function(){$log(', , , , , @@@ . @@@@@ @@@@@@ @@@@')}, 10800);
setTimeout(function(){$log(' ███   ████ █████ ███ ███ █    ')}, 10900);
setTimeout(function(){$log('█   █ █     █      █   █  █    ')}, 11000);
setTimeout(function(){$log('█████  ███  █      █   █  █    ')}, 11100);
setTimeout(function(){$log('█   █     █ █      █   █       ')}, 11200);
setTimeout(function(){$log('█   █ ████  █████ ███ ███ █    ')}, 11300);
setTimeout(function(){$log('<h3>Also no i dont know why the windows 93 logo looks so terrible</h3>')}, 11400);
setTimeout(function(){$log('')}, 11500);
setTimeout(function(){$log(' ███                    ')}, 11600);
setTimeout(function(){$log(' ███                    ')}, 11700);
setTimeout(function(){$log(' ███              ')}, 11800);
setTimeout(function(){$log('██████████████               ')}, 11900);
setTimeout(function(){$log('███ NOKIA  ███                     ')}, 12000);
setTimeout(function(){$log('███conecc™ ███             ')}, 12100);
setTimeout(function(){$log('██████████████          ')}, 12200);
setTimeout(function(){$log('█ 1 █ 2 █ 3 ██')}, 12300);
setTimeout(function(){$log('██████████████')}, 12400);
setTimeout(function(){$log('█ 4 █ 5 █ 6 ██')}, 12500);
setTimeout(function(){$log('██████████████')}, 12600);
setTimeout(function(){$log('█ 7 █ 8 █ 9 ██')}, 12700);
setTimeout(function(){$log('██████████████')}, 12800);
setTimeout(function(){$log('. .')}, 12900);
setTimeout(function(){$log('████.-.████')}, 13000);
setTimeout(function(){$log('█         █')}, 13100);
setTimeout(function(){$log('█         █')}, 13200);
setTimeout(function(){$log('█        █')}, 13300);
setTimeout(function(){$log('█         █')}, 13400);
setTimeout(function(){$log('█         █')}, 13500);
setTimeout(function(){$log('█         █')}, 13600);
setTimeout(function(){$log('█████O█████')}, 13700);
setTimeout(function(){$log('. .')}, 13800);
setTimeout(function(){$log('█████ █    █ █    █  █ ███')}, 13900);
setTimeout(function(){$log('  █   █    █  █  █     █  █')}, 14000);
setTimeout(function(){$log('  █   ██████   ██      █  █')}, 14100);
setTimeout(function(){$log('  █   █    █  █  █     █  █')}, 14200);
setTimeout(function(){$log('  █   █    █ █    █  █ ███')}, 14300);
setTimeout(function(){$log('. .')}, 14400);
setTimeout(function(){$log('███████')}, 14500);
setTimeout(function(){$log('   █')}, 14600);
setTimeout(function(){$log('  █ ')}, 14700);
setTimeout(function(){$log(' █')}, 14800);
setTimeout(function(){$log('█')}, 14900);
setTimeout(function(){$log('█')}, 15000);
setTimeout(function(){$log(' █')}, 15100);
setTimeout(function(){$log('  █')}, 15200);
setTimeout(function(){$log('   █')}, 15300);
setTimeout(function(){$log('   █')}, 15400);
setTimeout(function(){$log('  █  <--- i have no idea what this is')}, 15500);
setTimeout(function(){$log(' █')}, 15600);
setTimeout(function(){$log('█')}, 15700);
setTimeout(function(){$log('█████████')}, 15800);
setTimeout(function(){$log(' █      █')}, 15900);
setTimeout(function(){$log('  ███████')}, 16000);}, 1000)
